############# MySQL Config ############################################
spring.datasource.url=jdbc:mysql://localhost:3306/kollybistes
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

############# JWT Config ################################################
jwt.secret = 7Kvi32TZ0bGGUHLVDXS4gESzH1oOr7VoG2dfUrQYNhX17qFMc8O2uZiCbcMSN8W8mOJZW2tyQCCFWDqDjAeFXA
jwt.expiration.time=18000

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=f30d61b0e81ba7
spring.mail.password=58fe151f40ace9
spring.mail.protocol=smtp

bitcoin.network=org.bitcoin.regtest
bitcoin.rpc.user=root
bitcoin.rpc.password=password

exchange.api.url=https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=eth
bitcoin.fee.api.url=https://api.blockchair.com/bitcoin/stats
ethereum.gas.api.url=https://api.blockchair.com/ethereum/stats