# ==============================
# General Spring Boot Settings
# ==============================
server.port=8080
spring.application.name=Core

# ==============================
# Swagger Configuration
# ==============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# ==============================
# Database Configuration
# ==============================
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==============================
# Redis Configuration
# ==============================
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ==============================
# JWT Configuration
# ==============================
jwt.secret=
jwt.expiration.time=18000

# ==============================
# Bitcoin RPC Configuration
# ==============================
bitcoin.network=org.bitcoin.regtest
bitcoin.rpc.user=
bitcoin.rpc.password=

# ==============================
# System Wallets Configuration
# ==============================
system.btc.address=
system.btc.wallet-name=

system.eth.address=
system.eth.password=
system.eth.keystore.path=
system.eth.chainId=2025

# ==============================
# External APIs
# ==============================
exchange.api.url=https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=eth
bitcoin.fee.api.url=https://api.blockchair.com/bitcoin/stats
ethereum.gas.api.url=https://api.blockchair.com/ethereum/stats
