spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=kollybistes
spring.kafka.consumer.auto-offset-reset=earliest

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=f30d61b0e81ba7
spring.mail.password=58fe151f40ace9
spring.mail.protocol=smtp