# ==============================
# General Spring Boot Settings
# ==============================
server.port=8081
spring.application.name=Notification

# ==============================
# Mail Configuration
# ==============================
spring.mail.host=
spring.mail.port=2525
spring.mail.username=
spring.mail.password=
spring.mail.protocol=smtp

# ==============================
# Database Configuration
# ==============================
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=